### ISSUE TITLE
[PE-D][Tester E] [User Guide Bug] Image in Quick Start inconsistent with the actual product

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T17-2/tp#118]
### Image in Quick Guide inconsistent with the actual product

Marked as `Medium` as users might be confused and believe they download the wrong product.

What user expects ServiceTrack to look like (from image in User Guides' Quick Guide):
![Screenshot 2024-11-08 at 4.31.20 PM.png](https://raw.githubusercontent.com/xhamyo/ped/main/files/b5ca0808-1eab-4ee9-a068-f1ad48b90218.png)

What ServiceTrack actually looks like when run:
![Screenshot 2024-11-08 at 4.29.02 PM.png](https://raw.githubusercontent.com/xhamyo/ped/main/files/381e294a-5b73-462d-aa65-558fbb192512.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: xhamyo/ped#3

**Comment by muller317** [comment]
Solved
