### ISSUE TITLE
[PE-D][Tester D] Ui bug: Help command displays old userguide link

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T17-2/tp#147]
![image.png](https://raw.githubusercontent.com/muhdbhz/ped/main/files/2017391e-f208-457c-903b-61f721852caf.png)

Severity: Low because user guide could be obtained from the github, although this may be inconvenient

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: muhdbhz/ped#10

**Comment by muller317** [comment]
Duplicate of issue #126
