### ISSUE TITLE
[PE-D][Tester E] [Developer Guide Bug] Data Archiving proposed feature not updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T17-2/tp#152]
### Data Archiving proposed feature not updated

The Developer Guide is not updated for the Data Arching proposed feature. Marked as `High` because as a developer, I would have no direction and might not know the intended way it is supposed to be implemented.
![Screenshot 2024-11-08 at 5.19.45 PM.png](https://raw.githubusercontent.com/xhamyo/ped/main/files/e637a110-d6b4-4aab-bf17-3d3e71d7eec4.png)

-------------
Labels: `severity.High` `type.DocumentationBug`
original: xhamyo/ped#14

**Comment by muller317** [comment]
Not in scope
